import 'package:flutter/material.dart';
import 'package:flutter/gestures.dart';
import 'dart:ui';
import 'package:google_fonts/google_fonts.dart';
import 'package:myapp/utils.dart';
import 'package:myapp/design-system-wireframe/splash-screen.dart';
// import 'package:myapp/design-system-wireframe/inscription-avec-numro-de-tlphone.dart';
// import 'package:myapp/design-system-wireframe/login.dart';
// import 'package:myapp/design-system-wireframe/formulaire-dinscription.dart';
// import 'package:myapp/design-system-wireframe/nouveau-mot-de-passe.dart';
// import 'package:myapp/design-system-wireframe/mot-de-passe-oubli.dart';
// import 'package:myapp/design-system-wireframe/ajout-de-numro-de-tlphone.dart';
// import 'package:myapp/design-system-wireframe/ajout-de-numro-de-tlphone-HvJ.dart';
// import 'package:myapp/design-system-wireframe/code-de-vrification.dart';
// import 'package:myapp/design-system-wireframe/onboarding1.dart';
// import 'package:myapp/design-system-wireframe/onboarding2.dart';
// import 'package:myapp/design-system-wireframe/onboarding3.dart';
// import 'package:myapp/design-system-wireframe/localisation.dart';
// import 'package:myapp/design-system-wireframe/arrow-1.dart';
// import 'package:myapp/design-system-wireframe/arrow-2.dart';
// import 'package:myapp/design-system-wireframe/inactif.dart';
// import 'package:myapp/design-system-wireframe/actif.dart';
// import 'package:myapp/design-system-wireframe/numro-de-tlphone.dart';
// import 'package:myapp/design-system-wireframe/mot-de-passe.dart';
// import 'package:myapp/design-system-wireframe/nouveau-mot-de-passe-98v.dart';
// import 'package:myapp/design-system-wireframe/r-entrer-nouveau-mot-de-passe.dart';
// import 'package:myapp/design-system-wireframe/flicitation.dart';
// import 'package:myapp/design-system-wireframe/.dart';
// import 'package:myapp/design-system-wireframe/-8Z8.dart';
// import 'package:myapp/design-system-wireframe/-6wC.dart';
// import 'package:myapp/design-system-wireframe/-Sfc.dart';
// import 'package:myapp/design-system-wireframe/venta-app-1.dart';
// import 'package:myapp/design-system-wireframe/user-flow.dart';
// import 'package:myapp/design-system-wireframe/sketching.dart';
// import 'package:myapp/design-system-wireframe/mid-fi-wireframe.dart';
// import 'package:myapp/design-system-wireframe/partie-auth.dart';
// import 'package:myapp/design-system-wireframe/partie-client.dart';
// import 'package:myapp/design-system-wireframe/partie-vendeur.dart';
// import 'package:myapp/design-system-wireframe/variation-de-logo.dart';
// import 'package:myapp/design-system-wireframe/couleur-primaire.dart';
// import 'package:myapp/design-system-wireframe/design-system.dart';
// import 'package:myapp/design-system-wireframe/accueil.dart';
// import 'package:myapp/design-system-wireframe/outline-general-home.dart';
// import 'package:myapp/design-system-wireframe/outline-general-shopping-cart.dart';
// import 'package:myapp/design-system-wireframe/outline-general-bag.dart';
// import 'package:myapp/design-system-wireframe/outline-communication-user.dart';
// import 'package:myapp/design-system-wireframe/restaurants.dart';
// import 'package:myapp/design-system-wireframe/dtail-article.dart';
// import 'package:myapp/design-system-wireframe/panier.dart';
// import 'package:myapp/design-system-wireframe/supprimer-article.dart';
// import 'package:myapp/design-system-wireframe/organis-.dart';
// import 'package:myapp/design-system-wireframe/filtre.dart';
// import 'package:myapp/design-system-wireframe/organis--g6W.dart';
// import 'package:myapp/design-system-wireframe/splash-screen-vendeur.dart';
// import 'package:myapp/design-system-wireframe/splash-screen-vendeur-FXp.dart';
// import 'package:myapp/design-system-wireframe/acceuil-vendeur.dart';
// import 'package:myapp/design-system-wireframe/formulaire-dinscription-Uvn.dart';
// import 'package:myapp/design-system-wireframe/ajout-darticle.dart';
// import 'package:myapp/design-system-wireframe/asset-17-1.dart';
// import 'package:myapp/design-system-wireframe/asset-17-2.dart';
// import 'package:myapp/design-system-wireframe/asset-17-3.dart';
// import 'package:myapp/design-system-wireframe/asset-17-4.dart';
// import 'package:myapp/design-system-wireframe/asset-15.dart';
// import 'package:myapp/design-system-wireframe/asset-16.dart';
// import 'package:myapp/design-system-wireframe/rectangle-1381.dart';
// import 'package:myapp/design-system-wireframe/rectangle-1382.dart';
// import 'package:myapp/design-system-wireframe/rectangle-1383.dart';
// import 'package:myapp/design-system-wireframe/rectangle-1384.dart';
// import 'package:myapp/design-system-wireframe/material-theme.dart';
// import 'package:myapp/design-system-wireframe/frame-8273.dart';
// import 'package:myapp/design-system-wireframe/typography.dart';
// import 'package:myapp/design-system-wireframe/text-component.dart';
// import 'package:myapp/design-system-wireframe/icons.dart';
// import 'package:myapp/design-system-wireframe/desktop-1.dart';
// import 'package:myapp/design-system-wireframe/solid-.dart';
// import 'package:myapp/design-system-wireframe/components.dart';
// import 'package:myapp/design-system-wireframe/annonce.dart';
// import 'package:myapp/design-system-wireframe/plat-du-jour.dart';
// import 'package:myapp/design-system-wireframe/component-9.dart';
// import 'package:myapp/design-system-wireframe/component-6.dart';
// import 'package:myapp/design-system-wireframe/component-8.dart';
// import 'package:myapp/design-system-wireframe/outline-status-heart.dart';
// import 'package:myapp/design-system-wireframe/component-18.dart';
// import 'package:myapp/design-system-wireframe/vrification-de-ladmin.dart';
// import 'package:myapp/ui-mobile/mdi-phone.dart';
// import 'package:myapp/ui-mobile/partie-onboarding.dart';
// import 'package:myapp/ui-mobile/partie-auth.dart';
// import 'package:myapp/ui-mobile/partie-home.dart';
// import 'package:myapp/ui-mobile/partie-vendeur.dart';
// import 'package:myapp/ui-mobile/partie-statistique-vendeur.dart';
// import 'package:myapp/ui-mobile/partie-livreur.dart';
// import 'package:myapp/ui-mobile/partie-profile.dart';
// import 'package:myapp/ui-mobile/splash-screen.dart';
// import 'package:myapp/ui-mobile/auth-1.dart';
// import 'package:myapp/ui-mobile/sinscrire.dart';
// import 'package:myapp/ui-mobile/sidentifier.dart';
// import 'package:myapp/ui-mobile/auth-2.dart';
// import 'package:myapp/ui-mobile/auth-4.dart';
// import 'package:myapp/ui-mobile/auth-3.dart';
// import 'package:myapp/ui-mobile/onboarding1.dart';
// import 'package:myapp/ui-mobile/onboarding2.dart';
// import 'package:myapp/ui-mobile/onboarding3.dart';
// import 'package:myapp/ui-mobile/localisation.dart';
// import 'package:myapp/ui-mobile/accueil.dart';
// import 'package:myapp/ui-mobile/donner-avis.dart';
// import 'package:myapp/ui-mobile/restaurant.dart';
// import 'package:myapp/ui-mobile/filtre.dart';
// import 'package:myapp/ui-mobile/dtail-article.dart';
// import 'package:myapp/ui-mobile/panier.dart';
// import 'package:myapp/ui-mobile/confirmation-panier.dart';
// import 'package:myapp/ui-mobile/organis.dart';
// import 'package:myapp/ui-mobile/group-221.dart';
// import 'package:myapp/ui-mobile/splash-screen-vendeur.dart';
// import 'package:myapp/ui-mobile/mes-pages.dart';
// import 'package:myapp/ui-mobile/ajout-images.dart';
// import 'package:myapp/ui-mobile/page-sans-images-.dart';
// import 'package:myapp/ui-mobile/accueil-vendeur.dart';
// import 'package:myapp/ui-mobile/accueil-vendeur-Md4.dart';
// import 'package:myapp/ui-mobile/menu-modification-images.dart';
// import 'package:myapp/ui-mobile/photo-de-profil.dart';
// import 'package:myapp/ui-mobile/modifier-photo-de-profil.dart';
// import 'package:myapp/ui-mobile/menu-de-modification-photo-de-profil.dart';
// import 'package:myapp/ui-mobile/ajout-de-story.dart';
// import 'package:myapp/ui-mobile/stoory-ajoute-avec-succes.dart';
// import 'package:myapp/ui-mobile/menu-ajout-story.dart';
// import 'package:myapp/ui-mobile/photo-de-stry.dart';
// import 'package:myapp/ui-mobile/formulaire-dinscription.dart';
// import 'package:myapp/ui-mobile/ajout-darticle.dart';
// import 'package:myapp/ui-mobile/formulaire-story.dart';
// import 'package:myapp/ui-mobile/configuration.dart';
// import 'package:myapp/ui-mobile/button.dart';
// import 'package:myapp/ui-mobile/notification.dart';
// import 'package:myapp/ui-mobile/langues.dart';
// import 'package:myapp/ui-mobile/politique.dart';
// import 'package:myapp/ui-mobile/dconnection.dart';
// import 'package:myapp/ui-mobile/not-found.dart';
// import 'package:myapp/ui-mobile/contact-us.dart';
// import 'package:myapp/ui-mobile/contact-us-asC.dart';
// import 'package:myapp/ui-mobile/auth-1-R9c.dart';
// import 'package:myapp/ui-mobile/restaurant-rWv.dart';
// import 'package:myapp/ui-mobile/commandes-en-cours.dart';
// import 'package:myapp/ui-mobile/commandes.dart';
// import 'package:myapp/ui-mobile/commandes-mUv.dart';
// import 'package:myapp/ui-mobile/commandes-complte.dart';
// import 'package:myapp/ui-mobile/statistique.dart';
// import 'package:myapp/ui-mobile/commandes-oQN.dart';
// import 'package:myapp/ui-mobile/avis-des-clients.dart';
// import 'package:myapp/ui-mobile/notifications.dart';
// import 'package:myapp/ui-mobile/revenue.dart';
// import 'package:myapp/ui-mobile/story-1.dart';
// import 'package:myapp/ui-mobile/commandes-Uoc.dart';
// import 'package:myapp/ui-mobile/avis-client.dart';
// import 'package:myapp/ui-mobile/notifications-u7Y.dart';
// import 'package:myapp/ui-mobile/valider-commande.dart';
// import 'package:myapp/ui-mobile/valider-commande-o8e.dart';
// import 'package:myapp/ui-mobile/avis-envoy-avec-succes.dart';
// import 'package:myapp/ui-mobile/confirmation-commande-avec-succes.dart';
// import 'package:myapp/ui-mobile/confirmation-commande-avec-succes-Gqg.dart';
// import 'package:myapp/ui-mobile/splash-screen-8in.dart';
// import 'package:myapp/ui-mobile/profile-active.dart';
// import 'package:myapp/ui-mobile/profile-inactive.dart';
// import 'package:myapp/ui-mobile/login.dart';
// import 'package:myapp/ui-mobile/localisation-qWa.dart';
// import 'package:myapp/ui-mobile/historique.dart';
// import 'package:myapp/ui-mobile/outline-general-filter.dart';
// import 'package:myapp/ui-mobile/dtail-commande-valide.dart';
// import 'package:myapp/ui-mobile/dtail-commande-valide-L2E.dart';
// import 'package:myapp/ui-mobile/gain-9dt.dart';
// import 'package:myapp/ui-mobile/dashboard.dart';
// import 'package:myapp/ui-mobile/dashboard-oy4.dart';
// import 'package:myapp/ui-mobile/localisation-manuelle.dart';
// import 'package:myapp/ui-mobile/panier-fRC.dart';
// import 'package:myapp/ui-mobile/commentaire.dart';
// import 'package:myapp/ui-mobile/panier-yNA.dart';
// import 'package:myapp/ui-mobile/localisation-manuelle-CFk.dart';
// import 'package:myapp/ui-mobile/commentaire-STU.dart';
// import 'package:myapp/ui-mobile/group-1000002443.dart';
// import 'package:myapp/ui-mobile/description.dart';
// import 'package:myapp/ui-web/mdi-eye-outline.dart';
// import 'package:myapp/ui-web/dashboard-admin.dart';
// import 'package:myapp/ui-web/dashboard.dart';
// import 'package:myapp/ui-web/nb-client-totale.dart';
// import 'package:myapp/ui-web/clients.dart';
// import 'package:myapp/ui-web/livreurs.dart';
// import 'package:myapp/ui-web/vendeurs.dart';
// import 'package:myapp/ui-web/commandes.dart';
// import 'package:myapp/ui-web/historiques-des-transactions-des-sous-admin.dart';
// import 'package:myapp/ui-web/facture.dart';
// import 'package:myapp/ui-web/sous-admin.dart';
// import 'package:myapp/ui-web/historiques-des-transactions-des-livreurs.dart';
// import 'package:myapp/ui-web/profil.dart';
// import 'package:myapp/ui-web/add-sous-admin.dart';
// import 'package:myapp/ui-web/livreurs-RQW.dart';
// import 'package:myapp/ui-web/invitation.dart';
// import 'package:myapp/ui-web/dtail-invitation.dart';
// import 'package:myapp/ui-web/not-com-x.dart';
// import 'package:myapp/ui-web/variable-de-livraison-1d-km-taux-de-tax.dart';
// import 'package:myapp/ui-web/tax-totale-livreur-tax-totale-revenue-de-jour-pour-les-sous-admin.dart';
// import 'package:myapp/ui-web/login.dart';
// import 'package:myapp/ui-web/page-sous-admin.dart';
// import 'package:myapp/ui-web/page-detail.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
	@override
	Widget build(BuildContext context) {
	return MaterialApp(
		title: 'Flutter',
		debugShowCheckedModeBanner: false,
		scrollBehavior: MyCustomScrollBehavior(),
		theme: ThemeData(
		primarySwatch: Colors.blue,
		),
		home: Scaffold(
		body: SingleChildScrollView(
			child: Scene(),
		),
		),
	);
	}
}
